use_frameworks!

platform :ios, '8.0'

target 'ZZMakeWiFiManager_Example' do
  pod 'ZZMakeWiFiManager', :path => '../'

  target 'ZZMakeWiFiManager_Tests' do
    inherit! :search_paths

    
  end
end
